### ISSUE TITLE
Content representations

### ISSUE THREAD

**Issue by rasteiner** [getkirby/staticache#11]
I use content representations to dynamically create pdf versions of some pages. 
A request to `/mypage.pdf` caches the file to `static/mypage/index.pdf`, but of course the rewrite rule doesn't catch that. 

I don't know mod_rewrite enough to write a rule that "checks if `REQUEST_URI` has an extension that matches a `{basename}/index.{extension}`. 

So rewriting the plugin like this:

```diff
    public function file(string $key): string
    {
        $path      = dirname($key);
        $name      = F::name($key);
        $extension = F::extension($key);

        if ($name === 'home') {
            return $this->root . '/index.html';
        }

+       if ($extension === 'html') {
            return $this->root . '/' . $path . '/' . $name . '/index.' . $extension;
+       } else {
+           return $this->root . '/' . $path . '/' . $name . '.' . $extension;
+       }
    }
```

Gets me a `static/mypage.pdf`, and then adding

```aconf
# Staticache content representations
RewriteCond %{DOCUMENT_ROOT}/static/%{REQUEST_URI} -f
RewriteRule ^(.*) %{DOCUMENT_ROOT}/static/%{REQUEST_URI} [L]
```
to .htaccess makes the files work. 

However this kinda goes against #4 - since now people can request `/mypage/index.html`... ¯\\_(ツ)_/¯

Hence the issue instead of a PR.

**Comment by rasteiner** [comment]
Another issue is that the plugin still adds the html comment to the end of the file. This isn't a problem for pdf files, since those seem to tolerant with stuff added to the end of them (the pdf format uses a terminator to signal EOF), but other formats could be less resilient. 


```diff
    public function set(string $key, $value, int $minutes = 0): bool
    {
+       $extension = F::extension($key);
+       if($extension === 'html') {
            return F::write($this->file($key), $value['html'] . '<!-- static -->');
+       } else {
+           return F::write($this->file($key), $value['html']);
+       }
    }
```

**Comment by rasteiner** [comment]
... or here's another approach
https://github.com/rasteiner/htcache/blob/main/src/HTCache.php

**Comment by lukasbestle** [comment]
Another option would be to put the file in `mypage/mypage.pdf/index.pdf` and allow the PDF extension as directory index with:

```apache
DirectoryIndex index.html index.php index.json ...
```

**Comment by lukasbestle** [comment]
✅
