### ISSUE TITLE
Howto: plain php loader instead of apache/caddy/nginx configuration

### ISSUE THREAD

**Issue by bnomei** [getkirby/staticache#16]
Someone might find this useful... In case you can or do not want to configure you apache/caddy/nginx to load the html files you could also use plain php and add something like this before loading kirby. it should still be super super fast.

**index.php**
```php
<?php

function staticache()
{
    $dir = __DIR__ . '/site/cache/' . $_SERVER['SERVER_NAME'] . '/pages/';
    if (!file_exists($dir)) {
        return;
    }
    $staticache = rtrim($dir, '/') . (
        !empty($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] . '/' : '/'
        ) . 'index.html';
    if (file_exists($staticache)) {
        die(file_get_contents($staticache));
    }
}
staticache();

require __DIR__ . '/kirby/bootstrap.php';

echo (new Kirby)->render();
```

i wrapped it in a function to make it more readable but you could skip that.

**Comment by bastianallgeier** [comment]
I was wondering if we could somehow add it to the plugin, but I think there's really no faster way than to add it directly to the index.php

**Comment by jaro-io** [comment]
would there be any noticeable disadvantage in terms of speed compared to having it in the server config?

**Comment by bastianallgeier** [comment]
@jaro-io yes, going through PHP has a performance hit. It's not huge, but it's there. That's the superpower of static files. The server can serve them very quickly and efficiently.

**Comment by lukasbestle** [comment]
@bnomei Thanks for sharing the PHP loader, I think it's a great idea. I've built two versions that work with and without the header mode for full support of the plugin. Both versions are now in the `README`.
