### ISSUE TITLE
"ignore" rules misleading

### ISSUE THREAD

**Issue by jaro-io** [getkirby/staticache#17]
**hey everyone** ✨
love this plugin so far!

one thing that i found a little misleading is the following. at first i didn’t use any `ignore` rules and browsed my site, so cache files for each page were being created. afterwards i put a few pages on the `ignore` list. but it felt a bit strange when afterwards they were still loaded from cache.

after removing the affected page folders from the cache folder, it of course worked again. and it does make sense of course, if you look at how the plugin works. but still, i found that to be a little confusing. i don’t know if there’s a way to read the config and filter out ignored pages before even loading kirby. if not, i guess it would definitely make sense to at least update the documentation.

thank youuu!
♥️

**Comment by bastianallgeier** [comment]
The staticache layer is brutal. Once the files are there, they will get loaded by the server first. This is why the results are so good. If the server still had to look into PHP files first, all the performance benefits would be lost and it would no longer be static. I agree that we have to make this clearer in the docs though.
