### ISSUE TITLE
Does static cache need to be inside DOCUMENT_ROOT in a public folder setup?

### ISSUE THREAD

**Issue by intellent** [getkirby/staticache#18]
I’m running Kirby with a [public folder setup](https://getkirby.com/docs/guide/configuration#custom-folder-setup__public-folder-setup) on Apache.

The default `.htaccess` setup doesn’t work here, since the cache folder `/storage/cache` is outside the document root `/public`. Can I still get this to work? Or do I need to move the cache folder into the document root (i.e., `/public` directory)?

```Apache
RewriteCond %{DOCUMENT_ROOT}/storage/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html -f [NC]
RewriteRule ^(.*) %{DOCUMENT_ROOT}/storage/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html [L]

RewriteCond %{DOCUMENT_ROOT}/storage/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} -f [NC]
RewriteRule ^(.*) %{DOCUMENT_ROOT}/storage/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} [L]
```

**Comment by sciloqi** [comment]
I used this approach #16 with some minor adjustments:

```
function staticache()
{
    $dir = dirname(__DIR__) . '/storage/cache/' . $_SERVER['SERVER_NAME'] . '/pages';
    if (!file_exists($dir)) {
      return;
    }
    $staticache = rtrim($dir, '/') . (
        !empty($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] . '' : '/'
        ) . 'index.html';
    if (file_exists($staticache)) {
        die(file_get_contents($staticache));
    }
}
staticache();
```

**Comment by lukasbestle** [comment]
To make Apache pick up the cache files directly, they need to be inside the document root. So you have two alternatives:

- Either you set a custom root like stated in the plugin docs. The exact path inside the document root doesn't matter, so you can use any path that doesn't conflict with existing pages of the site.
- Or you keep the physical cache root as it is but create a symbolic link from the document root to the physical root. If your Apache setup is configured to follow the symbolic link, this is completely equivalent to a physical cache root inside the document root.

**Comment by intellent** [comment]
Thanks for clarifying.

So I ended up moving the static cache to the document root, since my hosting provider doesn’t allow symlinks. Here’s the setup:

`site/config/config.php`

```php
<?php

return [
    'ready' => function() {
        return [
            'cache' => [
                'pages' => [
                    'active'    => true,
                    'type'      => 'static',
                    'root'      => kirby()->root('index') . '/cache'
                ]
            ]
        ];
    }
];
```

`/public/.htaccess`

```Apache
RewriteCond %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html -f [NC]
RewriteRule ^(.*) %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html [L]

RewriteCond %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} -f [NC]
RewriteRule ^(.*) %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} [L]
```

Now the one thing that is missing, is blocking direct access to the `/cache` path. But somehow I didn’t get it to work. A simple redirect triggers in case of the rewrites, too.

**Comment by jonasfeige** [comment]
I tried the symlink solution but also couldn't quite get it to work, not sure why.

I have a `public/cache` symlink that points to `storage/cache` and this in my `/public/.htaccess`:

```
RewriteCond %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html -f [NC]
RewriteRule ^(.*) %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html [L]

RewriteCond %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} -f [NC]
RewriteRule ^(.*) %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} [L]
```

I am also symlinking the `media` folder, which is working as expected.

**Comment by jonasfeige** [comment]
> 

Do you have it working this way? Doesn't seem to do the trick for me.

**Comment by sciloqi** [comment]
@jonasfeige yes, but you need an Apache server, local php dev server is not working...

**Comment by jonasfeige** [comment]
@sciloqi Yeah, I'm running the site on Apache (uberspace). No timestamps in sight. Strange, I must be overlooking something. I'll give this another shot later.

**Comment by lukasbestle** [comment]
> Now the one thing that is missing, is blocking direct access to the `/cache` path. But somehow I didn’t get it to work. A simple redirect triggers in case of the rewrites, too.

@intellent You can achieve that with the `[END]` flag for the rule that blocks access to the `cache` folder:

```apache
RewriteRule ^cache/(.*) index.php [END]
```

Then Apache will not apply another rewrite iteration.

----

@jonasfeige Uberspace [restricted symlink support](http://blog.jonaspasche.com/2014/07/11/followsymlinks-vs-symlinksifownermatch/) in the Apache configuration because they could be used to access the data of other users on the same server. The last info I have is that they allow the option `SymLinksIfOwnerMatch`, but I'm not sure if it's enabled by default. So you may need to put `Options +SymLinksIfOwnerMatch` into your `.htaccess`.

**Comment by intellent** [comment]
> You can achieve that with the [END] flag for the rule that blocks access to the cache folder:

Thanks for getting back to me on this, @lukasbestle! However, if I add your suggested line to my `.htaccess` the static page cache gets generated on each request and are never served.

**Comment by lukasbestle** [comment]
@intellent Right, I'm sorry. I think you need to apply the flag not to the cache blocking rule but to the static cache rewrite rules. Otherwise the behavior is the opposite of what's intended.

**Comment by sciloqi** [comment]
@intellent @lukasbestle This is what I have tried and it seems to work, you don't even need the `[END]` in this case...

```
	RewriteCond %{THE_REQUEST} \s/+cache(/\S*)?\s [NC]
	RewriteRule ^cache/(.*) index.php

	RewriteCond %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html -f [NC]
	RewriteRule ^(.*) %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html [L]

	RewriteCond %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} -f [NC]
	RewriteRule ^(.*) %{DOCUMENT_ROOT}/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} [L]
```

**Comment by jonasfeige** [comment]
> @jonasfeige Uberspace [restricted symlink support](http://blog.jonaspasche.com/2014/07/11/followsymlinks-vs-symlinksifownermatch/) in the Apache configuration

Thanks for getting back to me @lukasbestle , but I don't think that's it, as I am using using symlinks for the media folder successfully. I still haven't been able to figure out why, but I can't get this to work with either the custom root, nor the symlink option. Must be something with uberspace though, as I remember using the pre-1.0 of this plugin successfully on an all-inkl server.

**Comment by bnomei** [comment]
`%{DOCUMENT_ROOT}` will not work as expected if folder does not match root. like in public folder setups where the cache should not be in same folder as `index.php`. the solution is to use the full path instead of the var. example...

```
RewriteBase /

RewriteCond /var/www/virtual/jfeige/jonasfeige.com/staticache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html -f [NC]
RewriteRule ^(.*) /var/www/virtual/jfeige/jonasfeige.com/staticache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html [L]

RewriteCond /var/www/virtual/jfeige/jonasfeige.com/staticache/%{SERVER_NAME}/pages/%{REQUEST_URI} -f [NC]
RewriteRule ^(.*) /var/www/virtual/jfeige/jonasfeige.com/staticache/%{SERVER_NAME}/pages/%{REQUEST_URI} [L]
```

see detailed explanation here:

https://forum.getkirby.com/t/static-cache-with-public-folder-setup/27902/6?u=bnomei
