### ISSUE TITLE
Multi-language setup

### ISSUE THREAD

**Issue by iskrisis** [getkirby/staticache#2]
Multi lang setup creates directories as
`url.language` meaning 

`/projects` creates `/static/projects.en/index.html`
`/cs/projects` creates `/static/projects.cs/index.html`

Folder structure needs to follow url structure.

**Comment by bnomei** [comment]
i refactored the `file` method and other parts to allow for multi-language setups in my fork but it was a bit to many changes for a PR so i decided to publish my own version for now. i will happily archive mine once the original plugin is updated.

https://github.com/bnomei/kirby3-staticache/blob/f7b39180b28bfbe69cfcd5727bddac3e21038f31/classes/StatiCache.php#L21

**Comment by lukasbestle** [comment]
✅
