### ISSUE TITLE
.htaccess rules combining -f with [NC] causes warning and has no effect

### ISSUE THREAD

**Issue by ovenum** [getkirby/staticache#28]
Looking at the apache error logs, trying to fix an unrelated issue, i noticed lots of warning messages for the staticache .htaccess rules.

`[rewrite:warn] RewriteCond: NoCase option for non-regex pattern '-f' is not supported and will be ignored.`

These are caused by the .htaccess rules from the staticache documentation

```apacheconf
RewriteCond %{DOCUMENT_ROOT}/site/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html -f [NC]
RewriteRule ^(.*) %{DOCUMENT_ROOT}/site/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html [END]

RewriteCond %{DOCUMENT_ROOT}/site/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} -f [NC]
RewriteRule ^(.*) %{DOCUMENT_ROOT}/site/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} [END]
```

Apparently combining `-f` with `[NC]` is not supported and, as the warning message says, will be ignored. 

The `[NC]` could be dropped without causing any breaking changes.
But it could be better to find a solution how get case insensitive matching for both rules.

**Apache Version**
Server version: Apache/2.4.58 (Unix

**Comment by grommasdietz** [comment]
Just ran into the same error logs and [researched a little](https://locall.host/make-url-case-insensitive/), maybe something like:

```apache config
# Serve cached index.html if it exists
RewriteCond %{DOCUMENT_ROOT}/site/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html -f
RewriteRule (.*) ${lc:$1} [R=301,L]
RewriteRule ^(.*) %{DOCUMENT_ROOT}/site/cache/%{SERVER_NAME}/pages/%{REQUEST_URI}/index.html [END]

# Serve cached page if it exists
RewriteCond %{DOCUMENT_ROOT}/site/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} -f
RewriteRule (.*) ${lc:$1} [R=301,L]
RewriteRule ^(.*) %{DOCUMENT_ROOT}/site/cache/%{SERVER_NAME}/pages/%{REQUEST_URI} [END]
```
(Eventually needs some adjustments, definitely not an expert in apache configuration.)

**Comment by lukasbestle** [comment]
Thanks, I've removed the NC option. I think it is not needed at all because the path itself (including the document root) is always of fixed case, the server name is always normalized to be lowercase and the request URI should not actually be case-insensitive (see the config examples for other servers).
