### ISSUE TITLE
Question: Make it a generator

### ISSUE THREAD

**Issue by fabianwohlfart** [getkirby/staticache#29]
I am just curious, with this type of cache. Wouldn't it be far away to build something like a generator for static websites?
Like the user hit's generate in the panel and a prerenderer goes through every route and then we use the output as a public dir?

Cheers,
F

**Comment by distantnative** [comment]
@fabianwohlfart that does exist too https://getkirby.com/plugins/d4l/static-site-generator but some people prefer this way over the other

**Comment by distantnative** [comment]
@fabianwohlfart you can add your upvote for this feature request https://kirby.nolt.io/24

**Comment by bastianallgeier** [comment]
Just to add a thought here. The huge advantage of staticache is that you can mix static with dynamic content.
