### ISSUE TITLE
How to ensure new page after update without http headers

### ISSUE THREAD

**Issue by psntr** [getkirby/staticache#30]
Strangely enough, not a lot of Apache hosting service has mod_asis enable, seems to be rather difficult to ask the hosting company to turn it on, so I can't really use http headers.

I'm wondering if there's a way another way to ensure new cached html page to be shown after an update, I notice that unless I do a hard fresh, sometimes the old page is still visible until a certain point. Is there a way to add a cachebust system for the generated html page?

Any advice would be appreciated.

**Comment by lukasbestle** [comment]
About `mod_asis`: I have the same experience, it's not one of the common Apache modules. You can still use the PHP loader then to use header support.

However I'm not quite sure how this relates to cachebusting. The Staticache is flushed like the normal page cache. But in addition to server-side caching, pages may also be cached by the client or by proxies in between. Staticache cannot do anything about that. You can customize the caching with the `Cache-Control` response header.
