### ISSUE TITLE
Return cached pages only if request method is GET or HEAD

### ISSUE THREAD

**Issue by tobiasfabian** [getkirby/staticache#32]
If the request method is POST, PUT, or similar, no cached pages should be returned.

The following could be added to the `index.php` (compare to [$page->isCacheable()](https://github.com/getkirby/kirby/blob/c1e6ff77b056774543f201035f5dab6a02bfdb3b/src/Cms/Page.php#L571))

```php
(function /* staticache */ () {
	// check if request method is not GET or HEAD
	if (in_array($_SERVER['REQUEST_METHOD'], ['GET', 'HEAD']) === false) {
		return;
	}

	// …
```

**Comment by intellent** [comment]
It’s probably useful to distinguish in the web server config between GET/HEAD and others. Maybe add this to the docs?

```apache
RewriteCond %{REQUEST_METHOD} ^(GET|HEAD)$
RewriteCond %{DOCUMENT_ROOT}/static/%{SERVER_NAME}/pages/%{REQUEST_URI} -f [NC]
RewriteRule ^(.*) %{DOCUMENT_ROOT}/static/%{SERVER_NAME}/pages/%{REQUEST_URI} [L]
```
